name: DNS Resolver

on:
  schedule:
    - cron: "*/5 * * * *"   # каждые 5 минут
  workflow_dispatch:         # возможность вручную запускать

jobs:
  resolve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run DNS resolver
        run: python3 resolve_github.py

      - name: Commit & push results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git add ipv4.txt cidr.txt || true

          if ! git diff --cached --quiet; then
            git commit -m "Update IP lists"
            git push
          else
            echo "No changes – nothing to commit."
